# AeroSpace is an i3-like tiling window manager for macOS
cask "aerospace"
# App to build and share containerised applications and microservices
cask "docker-desktop"
cask "font-monaspace"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# Control your tools with a few keystrokes
cask "raycast"
# Tool that provides consistent, highly configurable symbols for apps
cask "sf-symbols"
# High-performance multiplayer code editor
cask "zed"
